# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Get the fast C bindings:
#   gem install mysql
#   (on OS X: gem install mysql -- --include=/usr/local/lib)
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

production:
 adapter: mysql2
 database: myitcrm_production
 host: localhost
 username: root
 password: password
 encoding: utf8

#development:
#  adapter: mysql2
#  database: myitcrm_development
#  host: localhost
#  username: root
#  password: password
#  encoding: utf8

test:
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

